photos/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import *
from .models import Album, Photo

urlpatterns = [
    url(r'^$', AlbumLV.as_view(), name='index'),
    url(r'^album/$', AlbumLV.as_view(), name='album_list'),
    url(r'^album/(?P<pk>\d+)/$', AlbumDV.as_view(), name='album_detail'),
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),

    url(r'^admin/', admin.site.urls),

    # path : /photo/id/
    url(r'^photo/(?P<pk>\d+)/$', PhotoDV.as_view(), name='photo_detail'),


    # path : /album/add/
    url(r'^album/add/$', AlbumPhotoCV.as_view(), name='album_add'),

    # path : /album/change/
    url(r'^album/change/$', AlbumChangeLV.as_view(), name='album_change'),

    # path : /album/id/update/
    url(r'^album/(?P<pk>\d+)/update/$', AlbumPhotoUV.as_view(), name='album_update'),

    # path : /album/id/delete/
    url(r'^album/(?P<pk>\d+)/delete/$', AlbumDeleteView.as_view(), name='album_delete'),


    # path : /photo/add/
    url(r'^photo/add/$', PhotoCreateView.as_view(), name='photo_add'),

    # path : /photo/chage/
    url(r'^photo/change/$', PhotoChangeLV.as_view(), name='photo_change'),

    # path : /photo/id/update/
    url(r'^photo/(?P<pk>\d+)/update/$', PhotoUpdateView.as_view(), name='photo_update'),

    # path : /photo/id/delete/
    url(r'^photo/(?P<pk>\d+)/delete/$', PhotoDeleteView.as_view(), name='photo_delete'),

]

pytagram/urls.py
#pytagram/urls.py

from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from .views import MainView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    url(r'^$', MainView.as_view(), name='home'),
    url(r'^photo/', include('photos.urls', namespace='photo')),


    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserCreateDoneTV.as_view(), name='register_done'),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photos/models.py
from django.db import models

from django.core.urlresolvers import reverse
from .fields import ThumbnailImageField
from django.contrib.auth.models import User

# Create your models here.

class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail',args=(self.id,))


class Photo(models.Model):

    album = models.ForeignKey(Album)
    title = models.CharField(max_length=50)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Photo Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey(User, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail',args=(self.id,))

photos/forms.py
from .models import Album, Photo
from django.forms.models import inlineformset_factory

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
    fields = ['image', 'title', 'description'],
    extra = 2
    )

photos/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from .models import Album, Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from pytagram.views import LoginRequiredMixin

from .forms import PhotoInlineFormSet
from django.shortcuts import redirect

# Create your views here.

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo


# Add, Change, Update, Delete for Photo
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album','title','image','description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name= 'photos/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner = self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['album','title','image','description']
    success_url = reverse_lazy('photo:index')

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')


# Add, Chagne, Update, Delete for Album
# Change, Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photos/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner = self.request.user)

class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')


# inlineFormSet View
# Add, Update for Album
class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photos/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoCV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()

        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']

        for photoform in formset:
            photoform.instance.owner = self.request.user

        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())

        else:
            return self.render_to_response(self.get_context_data(form=form))

class AlbumPhotoUV(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['name', 'description']
    template_name = 'photos/album_form.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumPhotoUV, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST,
                self.request.FILES, instance = self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance = self.object)

        return context

        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.object.get_absolute_url())

        else:
            return self.render_to_response(self.get_context_data(form=form))

pytagram/views.py
#pytagram/views.py

from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

class MainView(TemplateView):
    template_name = 'main_page.html'

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

#p274
class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

photos/templates/photos/album_change_list.html
``{% extends "base.html" %}

{% block title %}album_change_list{% endblock %}

{% block content %}
<div id="content">
  <h1>Album Change - {{user}}</h1>

  <table class="change-list">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for item in object_list %}
    <tr>
      <td>{{ item.name }}</td>
      <td>{{ item.decription|linebreaks }}</td>
      <td>{{ item.owner }}</td>
      <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
      <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
    </tr>
    {% endfor %}

  </table>

</div>
{% endblock %}

photos/templates/photos/album_confirm_delete.html
``{% extends "base.html" %}

{% block title %}album_confirm_delete{% endblock %}


{% block content %}
<div id="content">
  <h1>Photo Delete</h1>

  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to deletre "{{ object }}" ?</p>
    <input type="submit" value="Confirm" />
  </form>

</div>
{% endblock %}

photos/templates/photos/album_detail.html
{% extends "base.html" %}

{% block title %}Album_detail{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

  <h2 style="display:inline">{{ object.name }}</h2>
  &emsp;<b><i>{{ object.description }}</i></b>

  <hr/>

  <div class="album-detail">
    {% for photo in object.photo_set.all %}
      <div class="album-detail-photo">
        <a href="{{ photo.get_absolute_url }}">
        <img class="thumbnail" src="{{ photo.image.thumb_url }}" />
      </a>
      <li>{{ photo.title }}</li>
      <li>{{ photo.upload_date|date:"Y.m.d"}}</li>
      </div>
    {% endfor %}

  </div>
</div>
{% endblock %}

photos/templates/photos/album_form.html
``{% extends "base.html" %}

{% block title %}album_form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
  <h1>Album-Photo inlineFormSet</h1>

  {% if form.is_multipart or formset.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
  {% else %}
    <form method="post" action=".">
  {% endif %}
  {% csrf_token %}

  {% if form.errors %}
  <p class="errornote">Worng! Please correct the FORM error(s) below.</p>
  {% endif %}
  {% if formset.errors %}
  <p class="errornote">Worng! Please correct the FORMSET error(s) below.</p>
  {% endif %}


  <h4>Create or Update Album contents.</h4>

  <fieldset class="aligned">
    <div class="form-row">
      {{ form.name.label_tag }} {{ form.name }}
    </div>
    <div class="form-row">
      {{ form.decription.label_tag }} {{ form.decription }}
    </div>
  </fieldset>


  <h4>Create or Update Photocontents.</h4>

  {{ formset.management_form }}
  {% for form in formset %}
    {{ form.id }}
  <fieldset class="aligned">
    <div class="form-row">
      {{ form.image.label_tag }} {{ form.image }}
    </div>
    <div class="form-row">
      {{ form.title.label_tag }} {{ form.title }}
    </div>
    <div class="form-row">
      {{ form.decription.label_tag }} {{ form.decription }}
    </div>
  </fieldset>
  {% endfor %}

  <div class="submit-row">
    <input type="submit", value="Submit"/>
  </div>

  <!script type="text/javascript">
  </form>

</div>
{% endblock %}

photos/templates/photos/album_list.html
{% extends "base.html" %}

{% block title %}Album_list{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

  {% for item in object_list %}

  <div class="clear_float">
    <h2 style="display:inline"><a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a></h2>
    &emsp;<b><i>{{ item.description }}</i></b>
  </div>

  <hr/>

  <div class="album-list">
    {% for photo in item.photo_set.all|slice:":5" %}
      <div class="album-list-photo">
        <a hred="{{photo_get_absolute_url }}">
        <img class="thumbnail" src="{{ photo.image.thumb_url}}" />
      </a>
      </div>
      {% endfor %}

  </div>
  {% endfor %}
</div>
{% endblock %}

photos/templates/photos/photo_change_list.html
``{% extends "base.html" %}

{% block title %}photo_change_list{% endblock %}

{% block content %}
<div id="content">
  <h1>Photo Change - {{user}}</h1>

  <table class="change-list">
    <tr>
      <th>Album</th>
      <th>Title</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>

    {% for item in object_list %}
    <tr>
      <td>{{ item.album }}</td>
      <td>{{ item.title }}</td>
      <td>{{ item.decription|linebreaks }}</td>
      <td>{{ item.owner }}</td>
      <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
      <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
    </tr>
    {% endfor %}

  </table>

</div>
{% endblock %}

photos/templates/photos/photo_confirm_delete.html
``{% extends "base.html" %}

{% block title %}photo_confirm_delete{% endblock %}


{% block content %}
<div id="content">
  <h1>Photo Delete</h1>

  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to deletre "{{ object }}" ?</p>
    <input type="submit" value="Confirm" />
  </form>
  
</div>
{% endblock %}

photos/templates/photos/photo_detail.html
``{% extends "base.html" %}

{% block title %}photo_detail{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/photo.css" %}{% endblock %}

{% block content %}
<div id="content">

  <h2>{{ object.title }}</h2>

  <table class="photo-detail">
  <tr>
  <td>
    <a href="{{ object.image.url }}">
    <img style="max-width:100%" src="{{ object.image.url }}" />
    </a>
  </td>

  <td>
  <ul>
    <li>Photo Description</li>
    {% if object.description %}
      <p>{{ object.description|linebreaks }}</p>
    {% else %}
      <p>blank</p>
    {% endif %}

    <p>{{ object.upload_date }}</p>
    <li>Album Name</li>
    <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>


  </ul>
  </td>
  </tr>
  </table>
</div>
{% endblock %}

photos/templates/photos/photo_form.html
``{% extends "base.html" %}

{% block title %}photo_form{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
  <h1>Photo Create/Update - {{user}}</h1>

  {% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
  {% else %}
    <form method="post" action=".">
  {% endif %}
  {% csrf_token %}

  {% if form.errors %}
  <p class="errornote">Worng! Please correct the FORM error(s) below.</p>
  {% endif %}

  <p>This is a cration or update form for your photo.</p>

  <fieldset class="aligned">
    <div class="form-row">
      {{ form.image.label_tag }} {{ form.image }}
    </div>

    <div class="form-row">
      {{ form.album.label_tag }} {{ form.album }}
      <button type="button"><a href="{% url 'photo:album_add' %}">Add Album</a></button>
    </div>

    <div class="form-row">
      {{ form.title.label_tag }} {{ form.title }}
    </div>

    <div class="form-row">
      {{ form.description.label_tag }} {{ form.description }}
    </div>
  </fieldset>

  <div class="submit-row">
    <input type="submit" value="Submit"/>    
  </div>


  </form>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang='ko'>

<head>
<title>{% block title %}{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

  <div id="header">
    <h2 class="maintitle"><a href="{% url 'home' %}">PYTAGRAM</a></h2>

    {% if user.is_active %}
    <h4 class="welcome">Welcome,
      <strong>{% firstof user.get_short_name user.get_username %}</strong> /
      <a href="{% url 'password_change' %}">Change Password</a> /
      <a href="{% url 'logout' %}">Logout</a>
    </h4>

    {% else %}
    <h4 class="welcome">Welcome, Guest! /
      <a href="{% url 'login' %}">Log-in</a> /
      <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}

  </div>


  <div id="menu">
    <h3><a href="{% url 'photo:index' %}">Photo</a></h3>

    <div id="menu_1">
      <h3><a href="#menu_1">Add_content</a></h3>
      <p><a href="{% url 'photo:album_add' %}">Album</a></p>
      <p><a href="{% url 'photo:photo_add' %}">Photo</a></p>
    </div>

    <div id="menu_2">
      <h3><a href="#menu_2">Change_content</a></h3>
      <p><a href="{% url 'photo:album_change' %}">Album</a></p>
      <p><a href="{% url 'photo:photo_change' %}">Photo</a></p>
    </div>

    <h3><a href="{% url 'admin:index' %}">Admin</a></h3>

  </div>


{% block content %}{% endblock %}

{% block footer %}
  <div id="footer">
    &copy; WYChoi 2018
  </div>
{% endblock %}

</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Pytagram{% endblock %}

{% load staticfiles %}
{% block content %}
<div id="content">
  <img src = "{% static "img/kground.jpg" %}", style='width:100%'>
  <h1>Pystagram</h1>

  <ul>

  <li><h3><a href="{% url 'photo:photo_add' %}"> Upload Your Picture </a></h3></li>
  <li><h3><a href="#"> Check your Picture </a></h3></li>
  <li><h3><a href="http://blog.naver.com/isac31">Go to Wooyong's blog</a></h3></li>

  </ul>
</div>
{% endblock content %}

templates/main_page.html
{% extends "base.html" %}

{% block title %}Pytagram{% endblock %}

{% load staticfiles %}
{% block content %}
<div id="content">
  <a href="{% url 'photo:index' %}"><img src = "{% static "img/kground.jpg" %}", style='width:100%'></a>
  <h1><font-style=italic>Welcome to Pytagram!</font-style></h1>

  <ul>

  <li><h3><a href="{% url 'photo:photo_add' %}"> Upload Your Picture </a></h3></li>
  <li><h3><a href="{% url 'photo:index' %}"> Check your Picture </a></h3></li>
  <li><h3><a href="http://blog.naver.com/isac31">Go to Wooyong's blog</a></h3></li>

  </ul>
</div>
{% endblock content %}